"""trip pickup

Revision ID: 04754c54cd74
Revises: 7c5ddeb6e8b6
Create Date: 2024-02-12 16:07:38.560891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04754c54cd74'
down_revision = '7c5ddeb6e8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_point', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('start_point')

    # ### end Alembic commands ###
