"""trips

Revision ID: 14ca00bdabc3
Revises: 79eacf32c0ec
Create Date: 2024-02-08 23:50:41.029826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ca00bdabc3'
down_revision = '79eacf32c0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoints', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('endpoints')

    # ### end Alembic commands ###
