"""sacco update

Revision ID: 79eacf32c0ec
Revises: a8aeabef75d8
Create Date: 2024-02-05 13:16:34.585462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79eacf32c0ec'
down_revision = 'a8aeabef75d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco', schema=None) as batch_op:
        batch_op.drop_column('sacco_verification_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sacco_verification_code', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
