"""trip

Revision ID: 7c5ddeb6e8b6
Revises: 14ca00bdabc3
Create Date: 2024-02-12 10:06:21.206693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5ddeb6e8b6'
down_revision = '14ca00bdabc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=50), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=False),
    sa.Column('ongoing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['route'], ['route.route_id'], ),
    sa.ForeignKeyConstraint(['vehicle_plate'], ['vehicle.no_plate'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
