"""trip in booking

Revision ID: 9d84ac7c4817
Revises: 190202fc9390
Create Date: 2024-02-13 14:31:51.433976

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d84ac7c4817"
down_revision = "190202fc9390"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.add_column(sa.Column("trip_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_booking_trip", "trip", ["trip_id"], ["trip_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("booking", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("trip_id")

    # ### end Alembic commands ###
