"""update vehicles

Revision ID: a8aeabef75d8
Revises: a0527a59565e
Create Date: 2024-02-04 09:00:44.883255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8aeabef75d8'
down_revision = 'a0527a59565e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
